# This is a basic workflow to help you get started with Actions

name: Deploy Bot

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deployment:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Configuration GIT name
      run: git config --global user.name ${{secrets.BOT_NAME}}
    - name: Configuration GIT email
      run: git config --global user.email ${{secrets.BOT_EMAIL}}
    - name: Creating .npmrc file
      run: echo "registry=https://registry.npmjs.org/" >> ~/.npmrc && echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc
      env:
        NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
    - name: Setting up the environment
      run: npm install && npm run build && sudo npm link
    - name: Deploying version
      run: sudo npm-deploy npm-package-deployer